### ISSUE TITLE
Přidat kontakt

### ISSUE THREAD

**Issue by Czechball** [bakalaborg/bakalab-web#2]
Už jsme založili oficiální support mail, support@bakalab.org. Mám svojí verzi contacts.html, ale očividně chceš udělat nějakou svojí, tak to tam pls přidej.

**Comment by jovanlanik** [comment]
O mailu vím, přidal jsem ho včera na GitHub k organizaci. Ohledně tvé verze contacts, byla špatně nastylovaná. Nadpisy měly špatné styly a link neměl žádný. Kontakty přidám ale až po přepracování některých věcí aby nebylo potom víc práce.
